name: pint

on:
  [push, workflow_dispatch]

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      -   name: Checkout code
          uses: actions/checkout@v2
          with:
            ref: ${{ github.head_ref }}

      -   name: Install Composer
          run: composer update -W

      -   name: Run Laravel Pint
          run: composer pint

      -   name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: fix code formatting
